# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kjeSpI03lQJNziXnUfsz_7whWGb8Gh92
"""

import random
import string

def generate_password():
    print("Welcome to the Password Generator!")


    try:
        password_length = int(input("Enter the desired length of the password: "))
        if password_length <= 0:
            print("Please enter a positive number.")
            return
    except ValueError:
        print("Invalid input. Please enter a number.")
        return


    print("\nChoose the complexity level:")
    print("1. Numbers only")
    print("2. Letters only")
    print("3. Letters and numbers")
    print("4. Letters, numbers, and special characters")

    try:
        complexity_level = int(input("Enter your choice (1-4): "))
        if complexity_level not in [1, 2, 3, 4]:
            print("Invalid choice. Please enter a number between 1 and 4.")
            return
    except ValueError:
        print("Invalid input. Please enter a number.")
        return


    if complexity_level == 1:
        character_pool = string.digits
    elif complexity_level == 2:
        character_pool = string.ascii_letters
    elif complexity_level == 3:
        character_pool = string.ascii_letters + string.digits
    elif complexity_level == 4:
        character_pool = string.ascii_letters + string.digits + string.punctuation


    generated_password = ''.join(random.choice(character_pool) for _ in range(password_length))

    print("\nGenerated Password:", generated_password)


generate_password()