# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kjeSpI03lQJNziXnUfsz_7whWGb8Gh92
"""

class ToDoList:
    def __init__(self):
        self.tasks_dict = {}
        self.current_task_id = 1

    def add_task(self, task_description):
        self.tasks_dict[self.current_task_id] = task_description
        print(f"Task '{task_description}' added successfully with ID: {self.current_task_id}")
        self.current_task_id += 1

    def update_task(self, task_id, updated_task_description):
        if task_id in self.tasks_dict:
            old_task_description = self.tasks_dict[task_id]
            self.tasks_dict[task_id] = updated_task_description
            print(f"Task ID {task_id} updated from '{old_task_description}' to '{updated_task_description}'")
        else:
            print(f"Task ID {task_id} not found.")

    def delete_task(self, task_id):
        if task_id in self.tasks_dict:
            removed_task_description = self.tasks_dict.pop(task_id)
            print(f"Task ID {task_id} ('{removed_task_description}') deleted successfully.")
        else:
            print(f"Task ID {task_id} not found.")

    def list_tasks(self):
        if not self.tasks_dict:
            print("No tasks in the list.")
        else:
            print("Current Tasks:")
            for task_id, task_description in self.tasks_dict.items():
                print(f"ID {task_id}: {task_description}")



todo_list = ToDoList()
todo_list.add_task("Buy groceries")
todo_list.add_task("Read a book")
todo_list.list_tasks()
todo_list.update_task(1, "Buy groceries and cook dinner")
todo_list.delete_task(2)
todo_list.list_tasks()